// Language model filenames shared by tessdata_fast and tessdata_best, tag 4.1.0.
// https://github.com/tesseract-ocr/tessdata_fast/tree/4.1.0
// https://github.com/tesseract-ocr/tessdata_best/tree/4.1.0
// English descriptions: https://tesseract-ocr.github.io/tessdoc/Data-Files-in-different-versions.html
// Native names: CLDR 48, including locales omitted from browser Intl data.
// https://github.com/unicode-org/cldr/tree/release-48/common/main
// Historical names are explicit: enm (Englisch), frm (françois), grc (Ἑλληνική),
// ita_old (italiano antico), kat_old (ძველი ქართული), spa_old (castellano antiguo).
// Tesseract's frk means German Fraktur, not the ISO language code for Frankish.
// Keep ordinary models before layout/font variants sharing their EPUB tag.
export const languages: readonly (readonly [
  ocrCode: string,
  tag: string,
  englishName: string,
  nativeName: string,
])[] = [
  ['afr', 'af', 'Afrikaans', 'Afrikaans'],
  ['amh', 'am', 'Amharic', 'አማርኛ'],
  ['ara', 'ar', 'Arabic', 'العربية'],
  ['asm', 'as', 'Assamese', 'অসমীয়া'],
  ['aze', 'az', 'Azerbaijani', 'azərbaycan'],
  ['aze_cyrl', 'az-Cyrl', 'Azerbaijani (Cyrillic)', 'азәрбајҹан (Кирил)'],
  ['bel', 'be', 'Belarusian', 'беларуская'],
  ['ben', 'bn', 'Bengali', 'বাংলা'],
  ['bod', 'bo', 'Tibetan', 'བོད་སྐད་'],
  ['bos', 'bs', 'Bosnian', 'bosanski'],
  ['bre', 'br', 'Breton', 'brezhoneg'],
  ['bul', 'bg', 'Bulgarian', 'български'],
  ['cat', 'ca', 'Catalan; Valencian', 'català'],
  ['ceb', 'ceb', 'Cebuano', 'Cebuano'],
  ['ces', 'cs', 'Czech', 'čeština'],
  ['chi_sim', 'zh-Hans', 'Chinese (Simplified)', '简体中文'],
  ['chi_sim_vert', 'zh-Hans', 'Chinese (Simplified, vertical)', '简体中文'],
  ['chi_tra', 'zh-Hant', 'Chinese (Traditional)', '繁體中文'],
  ['chi_tra_vert', 'zh-Hant', 'Chinese (Traditional, vertical)', '繁體中文'],
  ['chr', 'chr', 'Cherokee', 'ᏣᎳᎩ'],
  ['cos', 'co', 'Corsican', 'corsu'],
  ['cym', 'cy', 'Welsh', 'Cymraeg'],
  ['dan', 'da', 'Danish', 'dansk'],
  ['deu', 'de', 'German', 'Deutsch'],
  ['div', 'dv', 'Divehi', 'ދިވެހިބަސް'],
  ['dzo', 'dz', 'Dzongkha', 'རྫོང་ཁ'],
  ['ell', 'el', 'Greek (Modern)', 'Ελληνικά'],
  ['eng', 'en', 'English', 'English'],
  ['enm', 'enm', 'English (Middle)', 'Englisch'],
  ['epo', 'eo', 'Esperanto', 'Esperanto'],
  ['est', 'et', 'Estonian', 'eesti'],
  ['eus', 'eu', 'Basque', 'euskara'],
  ['fao', 'fo', 'Faroese', 'føroyskt'],
  ['fas', 'fa', 'Persian', 'فارسی'],
  ['fil', 'fil', 'Filipino', 'Filipino'],
  ['fin', 'fi', 'Finnish', 'suomi'],
  ['fra', 'fr', 'French', 'français'],
  ['frk', 'de', 'German (Fraktur)', 'Deutsch'],
  ['frm', 'frm', 'French (Middle)', 'françois'],
  ['fry', 'fy', 'Western Frisian', 'Frysk'],
  ['gla', 'gd', 'Scottish Gaelic', 'Gàidhlig'],
  ['gle', 'ga', 'Irish', 'Gaeilge'],
  ['glg', 'gl', 'Galician', 'galego'],
  ['grc', 'grc', 'Greek (Ancient)', 'Ἑλληνική'],
  ['guj', 'gu', 'Gujarati', 'ગુજરાતી'],
  ['hat', 'ht', 'Haitian Creole', 'Kreyòl Ayisyen'],
  ['heb', 'he', 'Hebrew', 'עברית'],
  ['hin', 'hi', 'Hindi', 'हिन्दी'],
  ['hrv', 'hr', 'Croatian', 'hrvatski'],
  ['hun', 'hu', 'Hungarian', 'magyar'],
  ['hye', 'hy', 'Armenian', 'հայերեն'],
  ['iku', 'iu', 'Inuktitut', 'ᐃᓄᒃᑎᑐᑦ'],
  ['ind', 'id', 'Indonesian', 'Indonesia'],
  ['isl', 'is', 'Icelandic', 'íslenska'],
  ['ita', 'it', 'Italian', 'italiano'],
  ['ita_old', 'it', 'Italian (Old)', 'italiano antico'],
  ['jav', 'jv', 'Javanese', 'Jawa'],
  ['jpn', 'ja', 'Japanese', '日本語'],
  ['jpn_vert', 'ja', 'Japanese (vertical)', '日本語'],
  ['kan', 'kn', 'Kannada', 'ಕನ್ನಡ'],
  ['kat', 'ka', 'Georgian', 'ქართული'],
  ['kat_old', 'oge', 'Georgian (Old)', 'ძველი ქართული'],
  ['kaz', 'kk', 'Kazakh', 'қазақ тілі'],
  ['khm', 'km', 'Khmer', 'ខ្មែរ'],
  ['kir', 'ky', 'Kyrgyz', 'кыргызча'],
  ['kmr', 'kmr-Latn', 'Kurmanji (Latin)', 'kurdî (kurmancî)'],
  ['kor', 'ko', 'Korean', '한국어'],
  ['kor_vert', 'ko', 'Korean (vertical)', '한국어'],
  ['lao', 'lo', 'Lao', 'ລາວ'],
  ['lat', 'la', 'Latin', 'Latina'],
  ['lav', 'lv', 'Latvian', 'latviešu'],
  ['lit', 'lt', 'Lithuanian', 'lietuvių'],
  ['ltz', 'lb', 'Luxembourgish', 'Lëtzebuergesch'],
  ['mal', 'ml', 'Malayalam', 'മലയാളം'],
  ['mar', 'mr', 'Marathi', 'मराठी'],
  ['mkd', 'mk', 'Macedonian', 'македонски'],
  ['mlt', 'mt', 'Maltese', 'Malti'],
  ['mon', 'mn', 'Mongolian', 'монгол'],
  ['mri', 'mi', 'Māori', 'Māori'],
  ['msa', 'ms', 'Malay', 'Melayu'],
  ['mya', 'my', 'Burmese', 'မြန်မာ'],
  ['nep', 'ne', 'Nepali', 'नेपाली'],
  ['nld', 'nl', 'Dutch', 'Nederlands'],
  ['nor', 'no', 'Norwegian', 'norsk'],
  ['oci', 'oc', 'Occitan', 'occitan'],
  ['ori', 'or', 'Odia', 'ଓଡ଼ିଆ'],
  ['pan', 'pa', 'Punjabi', 'ਪੰਜਾਬੀ'],
  ['pol', 'pl', 'Polish', 'polski'],
  ['por', 'pt', 'Portuguese', 'português'],
  ['pus', 'ps', 'Pashto', 'پښتو'],
  ['que', 'qu', 'Quechua', 'Runasimi'],
  ['ron', 'ro', 'Romanian', 'română'],
  ['rus', 'ru', 'Russian', 'русский'],
  ['san', 'sa', 'Sanskrit', 'संस्कृत भाषा'],
  ['sin', 'si', 'Sinhala', 'සිංහල'],
  ['slk', 'sk', 'Slovak', 'slovenčina'],
  ['slv', 'sl', 'Slovenian', 'slovenščina'],
  ['snd', 'sd', 'Sindhi', 'سنڌي'],
  ['spa', 'es', 'Spanish', 'español'],
  ['spa_old', 'osp', 'Spanish (Old)', 'castellano antiguo'],
  ['sqi', 'sq', 'Albanian', 'shqip'],
  ['srp', 'sr', 'Serbian', 'српски'],
  ['srp_latn', 'sr-Latn', 'Serbian (Latin)', 'srpski (latinica)'],
  ['sun', 'su', 'Sundanese', 'Basa Sunda'],
  ['swa', 'sw', 'Swahili', 'Kiswahili'],
  ['swe', 'sv', 'Swedish', 'svenska'],
  ['syr', 'syr', 'Syriac', 'ܣܘܪܝܝܐ'],
  ['tam', 'ta', 'Tamil', 'தமிழ்'],
  ['tat', 'tt', 'Tatar', 'татар'],
  ['tel', 'te', 'Telugu', 'తెలుగు'],
  ['tgk', 'tg', 'Tajik', 'тоҷикӣ'],
  ['tha', 'th', 'Thai', 'ไทย'],
  ['tir', 'ti', 'Tigrinya', 'ትግርኛ'],
  ['ton', 'to', 'Tongan', 'lea fakatonga'],
  ['tur', 'tr', 'Turkish', 'Türkçe'],
  ['uig', 'ug', 'Uyghur', 'ئۇيغۇرچە'],
  ['ukr', 'uk', 'Ukrainian', 'українська'],
  ['urd', 'ur', 'Urdu', 'اردو'],
  ['uzb', 'uz', 'Uzbek', 'o‘zbek'],
  ['uzb_cyrl', 'uz-Cyrl', 'Uzbek (Cyrillic)', 'ўзбекча (Кирил)'],
  ['vie', 'vi', 'Vietnamese', 'Tiếng Việt'],
  ['yid', 'yi', 'Yiddish', 'ייִדיש'],
  ['yor', 'yo', 'Yoruba', 'Èdè Yorùbá'],
];

export function languageOptions(kind: 'book' | 'ocr') {
  const options = new Map<
    string,
    { value: string; label: string; name: string }
  >();
  for (const [ocrCode, tag, englishName, nativeName] of languages) {
    const value = kind === 'ocr' ? ocrCode : tag;
    if (!options.has(value))
      options.set(value, {
        value,
        label: `${value} — ${englishName} — ${nativeName}`,
        name: englishName,
      });
  }
  return [...options.values()].sort(
    (a, b) =>
      a.name.localeCompare(b.name, 'en') ||
      a.value.localeCompare(b.value, 'en'),
  );
}
